// <auto-generated />
namespace LibraryManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_rel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_rel));
        
        string IMigrationMetadata.Id
        {
            get { return "201812242226416_Add_rel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
